[dependencies]

[package]
  cjc-version = "0.38.2"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "google_analytics"
  output-type = "static"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
